# <font color="maroon"><h4 align="center">Pandas Concat and Merge: Exercise</h4></font>

In [1]:
import pandas as pd

### <font color="purple">**Question1**</font>
- Read the 3 csv files provided into seperate dataframes (movies.csv to df_movies, financials.csv to df_financials, languages.csv to df_languages).
- show the top 3 rows for each dataframe.

In [48]:
#for movies.csv
df_movies= pd.read_csv("movies.csv")

#for financials.csv
df_financials= pd.read_csv("financials.csv")

#for languages.csv
df_languages= pd.read_csv("languages.csv")

In [49]:
#show top3 rows in df_movies
df_movies

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
5,106,Sholay,Bollywood,1975,8.1,United Producers,1
6,107,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,1
7,108,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,1
8,109,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,1
9,110,Bajirao Mastani,Bollywood,2015,7.2,NaN,1
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5
11,112,Inception,Hollywood,2010,8.8,Warner Bros. Pictures,5
12,113,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5
13,115,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,5
14,116,Gladiator,Hollywood,2000,8.5,Universal Pictures,5
15,117,Titanic,Hollywood,1997,7.9,Paramount Pictures,5
16,118,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,5
17,119,Avatar,Hollywood,2009,7.8,20th Century Fox,5
18,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5
19,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5
20,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5
21,123,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,5
22,124,Parasite,Hollywood,2019,8.5,NaN,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
25,127,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,7
26,128,Taare Zameen Par,Bollywood,2007,8.3,NaN,1
27,129,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,1
28,130,PK,Bollywood,2014,8.1,Vinod Chopra Films,1
29,131,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1
30,132,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2
31,133,RRR,Bollywood,2022,8.0,DVV Entertainment,2
32,134,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,2
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1
34,136,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,1
35,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5
36,138,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,5
37,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1

In [32]:
#show top3 rows in df_financials
df_financials.head(3)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD

In [33]:
#show top3 rows in df_languages
df_languages

   language_id lang_name
0            1     Hindi
1            2    Telugu
2            3   Kannada
3            4     Tamil
4            5   English
5            6    French
6            7   Bengali
7            8  Gujarati

### <font color="purple">**Question2**</font>
- Read the csv file 'new_movies.csv' and store it into dataframe 'df_new_movies'
- Now, concat the dataframes [df_movies, df_new_movies] and store the results again to df_movies. Make sure to ignore the index while concatenating

In [44]:
#read the csv file: 'new_movies.csv'
df_new_movies = pd.read_csv("new_movies.csv")

#show the datafram
df_new_movies

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,201,Pathaan,Bollywood,2023,6.6,Yash Raj Films,1
1,210,Vikram,Bollywood,2022,8.3,Raaj Kamal Films International,4
2,240,Black Panther: Wakanda Forever,Hollywood,200,6.9,Marvel Studios,5

In [52]:
#concat the two dataframes ['df_movies', df_new_movies]
df_movies = pd.concat([df_movies, df_new_movies])

#show the last 5 rows
df_movies.tail()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
43,210,Vikram,Bollywood,2022,8.3,Raaj Kamal Films International,4
44,240,Black Panther: Wakanda Forever,Hollywood,200,6.9,Marvel Studios,5
0,201,Pathaan,Bollywood,2023,6.6,Yash Raj Films,1
1,210,Vikram,Bollywood,2022,8.3,Raaj Kamal Films International,4
2,240,Black Panther: Wakanda Forever,Hollywood,200,6.9,Marvel Studios,5

### <font color="purple">**Question3**</font>

- Merge the dataframe df_movies with the df_languages on 'language_id'.
- Make sure you perform a **inner** join here.
- Store the result again to df_movies

In [53]:
#perform the join operation
df_movies = pd.merge(df_movies, df_languages, on = 'language_id', how = 'inner')

#show the top 5 rows
df_movies.head()

#show the top 5 rows

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,lang_name
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,Kannada
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,English
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,English
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,English
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,English

### <font color="purple">**Question4**</font>

- Merge the dataframe df_movies with the df_financials on 'movie_id'.
- Make sure you perform a **left** join here.
- Store the result again to df_movies

In [54]:
#perform the join operation
df_movies = pd.merge(df_movies, df_financials, on = 'movies_id', how = 'left')

#show the top 5 rows
df_movies.head(5)

#show the last 5 rows

KeyError: 'movies_id'

### <font color="purple">**Question5**</font>

- Save the 'df_movies' dataframe with name 'final_complete_data.csv'.
- Only take the columns 'movie_id', 'title', 'lang_name', 'budget', 'revenue', 'currency'
- set the index to False while saving the dataframe

In [71]:
#save the dataframe to 'final_complete_data.csv'