## <font color="maroon"><h4 align="center"> DataFrame Basics (Exercise)</font>

**Peter Pandey** arrived in Bangalore(a city in India) with the aim of finding a suitable house that fits his budget and location preferences. He has some queries related to house selection and is seeking solutions.

Help Peter Pandey to answer his questions and you are provided with a sample dataset of house information that contain area_type, availability, location, size, society, total_sqft, bath, balcony, and price.

In [1]:
import pandas as pd

### <font color="purple">**Question1**</font>
- Read the csv file 'bengaluru_house_prices.csv' and store it in variable 'df'.
- print the number of rows and columns in it
- print the Top 5 rows

In [10]:
#read the csv file
df = pd.read_csv("bengaluru_house_prices.csv")


#show the number of rows and columns in dataframe 'df'
len(df)
len(df.columns)


df.head(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,Ready To Move,Ambedkar Nagar,3 BHK,NaN,1920,4.0,2.0,121.0
1,Plot Area,18-Aug,Hulimavu,4 Bedroom,ValleCi,1500,4.0,3.0,192.0
2,Super built-up Area,Ready To Move,Kalkere,2 BHK,Sothin,925,2.0,1.0,55.0
3,Plot Area,Ready To Move,Kodigehalli,2 Bedroom,NaN,500,1.0,0.0,55.0
4,Super built-up Area,Ready To Move,Harlur,2 BHK,Prncyrn,1174,2.0,1.0,74.0

### <font color="purple">**Question2**</font>
- show the unique categories present in **'area_type'** and **'size'** columns

In [11]:
#unique values in 'area_type' column
df.area_type.unique()

<StringArray>
['Super built-up  Area', 'Plot  Area', 'Built-up  Area', 'Carpet  Area']
Length: 4, dtype: str

In [13]:
#unique values in 'size' column
df["size"].unique()

<StringArray>
[    '3 BHK', '4 Bedroom',     '2 BHK', '2 Bedroom',     '1 BHK',     '5 BHK',
 '3 Bedroom', '5 Bedroom', '1 Bedroom']
Length: 9, dtype: str

### <font color="purple">**Question3**</font>
- Filter data which have **'2 BHK'** house size and area_type of **'Super built-up  Area'**
- Also get the count of such rows

In [17]:
#filter the data
df[(df["size"]=="2 BHK")& (df["area_type"]=="Super built-up  Area")]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
2,Super built-up Area,Ready To Move,Kalkere,2 BHK,Sothin,925,2.0,1.0,55.00
4,Super built-up Area,Ready To Move,Harlur,2 BHK,Prncyrn,1174,2.0,1.0,74.00
5,Super built-up Area,Ready To Move,Jakkur,2 BHK,HRaniIb,1202,2.0,1.0,79.00
8,Super built-up Area,Ready To Move,Thubarahalli,2 BHK,ShdhiSa,1200,2.0,2.0,79.55
11,Super built-up Area,17-Oct,Ramagondanahalli,2 BHK,ViistLa,1235,2.0,1.0,52.04
14,Super built-up Area,Ready To Move,Budigere,2 BHK,PrityTr,1153,2.0,2.0,56.55
21,Super built-up Area,18-Apr,Sai Gardens,2 BHK,NaN,1120,2.0,2.0,40.00
24,Super built-up Area,Ready To Move,Neeladri Nagar,2 BHK,GeereEc,1363,2.0,2.0,68.00
25,Super built-up Area,Ready To Move,Sarjapur,2 BHK,NaN,1175,2.0,2.0,42.00
32,Super built-up Area,Ready To Move,Yelahanka,2 BHK,Pyikad,1274,2.0,2.0,48.42
33,Super built-up Area,Ready To Move,AECS Layout,2 BHK,CMard B,1005,2.0,1.0,55.00
35,Super built-up Area,17-Mar,Varthur,2 BHK,Uptusol,1385,2.0,3.0,80.00
37,Super built-up Area,Ready To Move,Seegehalli,2 BHK,Sriferi,1176,2.0,2.0,50.00
38,Super built-up Area,Ready To Move,Electronic City,2 BHK,GMown E,770,1.0,1.0,40.00
39,Super built-up Area,Ready To Move,Banashankari,2 BHK,NaN,1195,2.0,1.0,35.84
41,Super built-up Area,Ready To Move,Kambipura,2 BHK,Prrtht,883,2.0,1.0,37.00
42,Super built-up Area,Ready To Move,Haralur Road,2 BHK,RInceeg,1243,2.0,2.0,46.00
45,Super built-up Area,Ready To Move,Basavangudi,2 BHK,NaN,1200,2.0,3.0,120.00
48,Super built-up Area,Ready To Move,Choodasandra,2 BHK,Maidsr,1075,2.0,2.0,45.00
49,Super built-up Area,Ready To Move,Doctors Layout,2 BHK,NaN,1225,2.0,1.0,47.00

In [18]:
#show the number of rows for the filtered data
len(df)

50

### <font color="purple">**Question4**</font>
- Add a new column **'price_category'** which contain a category based on the price of house.
- If price of house is less than 80, **"Affordable"**, otherwise **"High Cost"**

In [19]:
#Add the column 'price_category'
df["price_category"] = df["price"].apply(
    lambda x: "Affordable" if x<80 else "High Cost"
)

In [22]:
#show the updated dataframe: top5 rows
df.head(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,price_category
0,Super built-up Area,Ready To Move,Ambedkar Nagar,3 BHK,NaN,1920,4.0,2.0,121.0,High Cost
1,Plot Area,18-Aug,Hulimavu,4 Bedroom,ValleCi,1500,4.0,3.0,192.0,High Cost
2,Super built-up Area,Ready To Move,Kalkere,2 BHK,Sothin,925,2.0,1.0,55.0,Affordable
3,Plot Area,Ready To Move,Kodigehalli,2 Bedroom,NaN,500,1.0,0.0,55.0,Affordable
4,Super built-up Area,Ready To Move,Harlur,2 BHK,Prncyrn,1174,2.0,1.0,74.0,Affordable

### <font color="purple">**Question5**</font>

- Get all the rows that has prices greater than **mean/average** price of all houses

In [25]:
#write condition here
df.mean(

C:\Users\bhati\AppData\Local\Temp\ipykernel_5416\466597422.py:2: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  df.mean(df["price"])

TypeError: cannot use 'pandas.Series' as a dict key (unhashable type: 'Series')