In [122]:
import pandas as pd
df = pd.read_csv("AB_NYC_2019.csv")

In [123]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [124]:
df.drop(["id","host_id",	"neighbourhood_group",	"neighbourhood",	"latitude",	"longitude","number_of_reviews","last_review",	"reviews_per_month",	"calculated_host_listings_count"], axis="columns",inplace=True)

In [125]:
df

,name,host_name,room_type,price,minimum_nights,availability_365
0,Clean & quiet apt home by the park,John,Private room,149,1,365
1,Skylit Midtown Castle,Jennifer,Entire home/apt,225,1,355
2,THE VILLAGE OF HARLEM....NEW YORK !,Elisabeth,Private room,150,3,365
3,Cozy Entire Floor of Brownstone,LisaRoxanne,Entire home/apt,89,1,194
4,Entire Apt: Spacious Studio/Loft by central park,Laura,Entire home/apt,80,10,0
...,...,...,...,...,...,...
48890,Charming one bedroom - newly renovated rowhouse,Sabrina,Private room,70,2,9
48891,Affordable room in Bushwick/East Williamsburg,Marisol,Private room,40,4,36
48892,Sunny Studio at Historical Neighborhood,Ilgar & Aysel,Entire home/apt,115,10,27
48893,43rd St. Time Square-cozy single bed,Taz,Shared room,55,1,2
48894,Trendy duplex in the very heart of Hell's Kitchen,Christophe,Private room,90,7,23

In [126]:
df.isna().sum()

name                16
host_name           21
room_type            0
price                0
minimum_nights       0
availability_365     0
dtype: int64

In [127]:
df2 = df.dropna()

In [128]:
df2.isna().sum()

name                0
host_name           0
room_type           0
price               0
minimum_nights      0
availability_365    0
dtype: int64

In [129]:
min_throught, max_throught = df2["price"].quantile([0.1,0.99])
min_throught, max_throught

(49.0, 799.0)

In [130]:
df2[df2["price"] <min_throught]

,name,host_name,room_type,price,minimum_nights,availability_365
28,"SPACIOUS, LOVELY FURNISHED MANHATTAN BEDROOM",Shon,Private room,44,3,311
36,Clean and Quiet in Brooklyn,Vt,Private room,35,60,365
39,LowerEastSide apt share shortterm 1,Ben,Shared room,40,1,188
149,Sunny Room in Old Historical Brooklyn Townhouse,Obed,Private room,44,8,280
171,Room with a View,Waundell,Private room,40,1,353
...,...,...,...,...,...,...
48871,A LARGE ROOM - 1 MONTH MINIMUM - WASHER&DRYER,Ozzy Ciao,Private room,35,29,31
48877,Studio sized room with beautiful light,Melanie,Private room,42,7,16
48878,Room for rest,Jeerathinan,Private room,45,1,172
48882,Bushwick _ Myrtle-Wyckoff,Luisa,Private room,40,20,31
48891,Affordable room in Bushwick/East Williamsburg,Marisol,Private room,40,4,36

In [131]:
df2[df2["price"] >max_throught]

,name,host_name,room_type,price,minimum_nights,availability_365
85,perfect for a family or small group,Maggie,Entire home/apt,800,1,7
496,Luxury 2Bed/2.5Bath Central Park View,Henry,Entire home/apt,2000,30,0
662,Heart & Soul of Greenwich Village,Rhona,Entire home/apt,850,3,249
762,6 Bedroom Landmark West Village Townhouse,West Village,Entire home/apt,1300,5,297
780,#1 Yellow Block BnB/see at Net Flix Show Stay ...,Gordy,Entire home/apt,800,4,257
...,...,...,...,...,...,...
48304,Next to Times Square/Javits/MSG! Amazing 1BR!,Rogelio,Entire home/apt,2999,30,222
48305,2BR Near Museum Mile! Upper East Side!,Mary Rotsen,Entire home/apt,1999,30,270
48523,"Tasteful & Trendy Brooklyn Brownstone, near Train",Sandy,Entire home/apt,1369,1,349
48535,"Stunning & Stylish Brooklyn Luxury, near Train",Urvashi,Entire home/apt,1749,1,303
48839,Massage Spa. Stay overnight. Authors Artist dr...,Richard,Private room,800,1,23

In [145]:
df2 = df2[(df['price']>min_throught) & (df2['price']<max_throught)]
df2.shape

C:\Users\bhati\AppData\Local\Temp\ipykernel_9704\3889856348.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[(df['price']>min_throught) & (df2['price']<max_throught)]

(42908, 7)

In [135]:
df2["z_score"] = (df2.price - df2.price.mean())/df2.price.std()
df2.head(5)

,name,host_name,room_type,price,minimum_nights,availability_365,z_score
0,Clean & quiet apt home by the park,John,Private room,149,1,365,0.003431
1,Skylit Midtown Castle,Jennifer,Entire home/apt,225,1,355,0.741568
2,THE VILLAGE OF HARLEM....NEW YORK !,Elisabeth,Private room,150,3,365,0.013144
3,Cozy Entire Floor of Brownstone,LisaRoxanne,Entire home/apt,89,1,194,-0.579308
4,Entire Apt: Spacious Studio/Loft by central park,Laura,Entire home/apt,80,10,0,-0.666719

In [139]:
df2[df2["z_score"]<4]

,name,host_name,room_type,price,minimum_nights,availability_365,z_score
0,Clean & quiet apt home by the park,John,Private room,149,1,365,0.003431
1,Skylit Midtown Castle,Jennifer,Entire home/apt,225,1,355,0.741568
2,THE VILLAGE OF HARLEM....NEW YORK !,Elisabeth,Private room,150,3,365,0.013144
3,Cozy Entire Floor of Brownstone,LisaRoxanne,Entire home/apt,89,1,194,-0.579308
4,Entire Apt: Spacious Studio/Loft by central park,Laura,Entire home/apt,80,10,0,-0.666719
...,...,...,...,...,...,...,...
48889,QUIT PRIVATE HOUSE,Michael,Private room,65,1,163,-0.812404
48890,Charming one bedroom - newly renovated rowhouse,Sabrina,Private room,70,2,9,-0.763842
48892,Sunny Studio at Historical Neighborhood,Ilgar & Aysel,Entire home/apt,115,10,27,-0.326788
48893,43rd St. Time Square-cozy single bed,Taz,Shared room,55,1,2,-0.909527
48894,Trendy duplex in the very heart of Hell's Kitchen,Christophe,Private room,90,7,23,-0.569596

In [140]:
df2[df2["z_score"]>4]

,name,host_name,room_type,price,minimum_nights,availability_365,z_score
299,Unique spacious loft on the Bowery,Alicia,Entire home/apt,575,2,298,4.140881
345,The Brooklyn Waverly,Sahr,Entire home/apt,650,5,365,4.869305
365,2 BR w/ Terrace @ Box House Hotel,The Box House Hotel,Private room,599,3,60,4.373977
653,4 BEDROOM -2BATHRM WEST VILLAGE DUPLEX TOWNHOUSE,West Village,Entire home/apt,700,3,296,5.354922
684,2 BR Duplex @ Box House Hotel,The Box House Hotel,Private room,599,3,60,4.373977
...,...,...,...,...,...,...,...
48310,ROMANTIC SUNSET YACHT CRUISE & FIREWORKS,Buddy,Entire home/apt,600,1,44,4.383689
48343,"Sunny, Spacious 2-bd Chelsea Apt",Olive,Entire home/apt,750,1,89,5.840538
48378,Sunny SoHo Penthouse w/ Pvt. Terrace!,Michael,Entire home/apt,600,3,179,4.383689
48697,HUGE LUXURY CONDO – INCREDIBLE WATER VIEWS,Layla,Entire home/apt,750,4,174,5.840538
48757,Luxury & Spacious 1500 ft² MANHATTAN Townhouse,Ellen,Entire home/apt,700,3,37,5.354922

In [142]:
df2 = df2[(df2.z_score>-4) & (df2.z_score<4)]
df2

,name,host_name,room_type,price,minimum_nights,availability_365,z_score
0,Clean & quiet apt home by the park,John,Private room,149,1,365,0.003431
1,Skylit Midtown Castle,Jennifer,Entire home/apt,225,1,355,0.741568
2,THE VILLAGE OF HARLEM....NEW YORK !,Elisabeth,Private room,150,3,365,0.013144
3,Cozy Entire Floor of Brownstone,LisaRoxanne,Entire home/apt,89,1,194,-0.579308
4,Entire Apt: Spacious Studio/Loft by central park,Laura,Entire home/apt,80,10,0,-0.666719
...,...,...,...,...,...,...,...
48889,QUIT PRIVATE HOUSE,Michael,Private room,65,1,163,-0.812404
48890,Charming one bedroom - newly renovated rowhouse,Sabrina,Private room,70,2,9,-0.763842
48892,Sunny Studio at Historical Neighborhood,Ilgar & Aysel,Entire home/apt,115,10,27,-0.326788
48893,43rd St. Time Square-cozy single bed,Taz,Shared room,55,1,2,-0.909527
48894,Trendy duplex in the very heart of Hell's Kitchen,Christophe,Private room,90,7,23,-0.569596

In [144]:
df2.shape

(42908, 7)