In [31]:
import pandas as pd
df = pd.read_csv("AB_NYC_2019.csv")

In [32]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [33]:
df.drop(["id","host_id","host_name",	"neighbourhood_group",	"neighbourhood",	"latitude",	"longitude","number_of_reviews","last_review",	"reviews_per_month",	"calculated_host_listings_count"], axis="columns",inplace=True)

In [34]:
df

,name,room_type,price,minimum_nights,availability_365
0,Clean & quiet apt home by the park,Private room,149,1,365
1,Skylit Midtown Castle,Entire home/apt,225,1,355
2,THE VILLAGE OF HARLEM....NEW YORK !,Private room,150,3,365
3,Cozy Entire Floor of Brownstone,Entire home/apt,89,1,194
4,Entire Apt: Spacious Studio/Loft by central park,Entire home/apt,80,10,0
...,...,...,...,...,...
48890,Charming one bedroom - newly renovated rowhouse,Private room,70,2,9
48891,Affordable room in Bushwick/East Williamsburg,Private room,40,4,36
48892,Sunny Studio at Historical Neighborhood,Entire home/apt,115,10,27
48893,43rd St. Time Square-cozy single bed,Shared room,55,1,2
48894,Trendy duplex in the very heart of Hell's Kitchen,Private room,90,7,23

In [35]:
df.isna().sum()

name                16
room_type            0
price                0
minimum_nights       0
availability_365     0
dtype: int64

In [36]:
df2 = df.copy()
df2 = df.dropna()

In [37]:
df2.isna().sum()

name                0
room_type           0
price               0
minimum_nights      0
availability_365    0
dtype: int64

In [38]:
df2["price_per_night"] = df2["price"]/df2["minimum_nights"]

In [39]:
df2

,name,room_type,price,minimum_nights,availability_365,price_per_night
0,Clean & quiet apt home by the park,Private room,149,1,365,149.000000
1,Skylit Midtown Castle,Entire home/apt,225,1,355,225.000000
2,THE VILLAGE OF HARLEM....NEW YORK !,Private room,150,3,365,50.000000
3,Cozy Entire Floor of Brownstone,Entire home/apt,89,1,194,89.000000
4,Entire Apt: Spacious Studio/Loft by central park,Entire home/apt,80,10,0,8.000000
...,...,...,...,...,...,...
48890,Charming one bedroom - newly renovated rowhouse,Private room,70,2,9,35.000000
48891,Affordable room in Bushwick/East Williamsburg,Private room,40,4,36,10.000000
48892,Sunny Studio at Historical Neighborhood,Entire home/apt,115,10,27,11.500000
48893,43rd St. Time Square-cozy single bed,Shared room,55,1,2,55.000000
48894,Trendy duplex in the very heart of Hell's Kitchen,Private room,90,7,23,12.857143

In [48]:
min_throught, max_throught = df2["price_per_night"].quantile([0.8,0.999])
min_throught, max_throught

(96.66666666666667, 2000.0)

In [49]:
df2[df2["price_per_night"] <min_throught]

,name,room_type,price,minimum_nights,availability_365,price_per_night
2,THE VILLAGE OF HARLEM....NEW YORK !,Private room,150,3,365,50.000000
3,Cozy Entire Floor of Brownstone,Entire home/apt,89,1,194,89.000000
4,Entire Apt: Spacious Studio/Loft by central park,Entire home/apt,80,10,0,8.000000
5,Large Cozy 1 BR Apartment In Midtown East,Entire home/apt,200,3,129,66.666667
6,BlissArtsSpace!,Private room,60,45,0,1.333333
...,...,...,...,...,...,...
48890,Charming one bedroom - newly renovated rowhouse,Private room,70,2,9,35.000000
48891,Affordable room in Bushwick/East Williamsburg,Private room,40,4,36,10.000000
48892,Sunny Studio at Historical Neighborhood,Entire home/apt,115,10,27,11.500000
48893,43rd St. Time Square-cozy single bed,Shared room,55,1,2,55.000000
48894,Trendy duplex in the very heart of Hell's Kitchen,Private room,90,7,23,12.857143

In [80]:
df2[df2["price_per_night"] >max_throught]

,name,room_type,price,minimum_nights,availability_365,price_per_night
2698,Beautiful 1 Bedroom in Nolita/Soho,Entire home/apt,5000,1,365,5000.0
3695,NYC SuperBowl Wk 5 Bdrs River View,Entire home/apt,4000,1,0,4000.0
3720,"SuperBowl Penthouse Loft 3,000 sqft",Entire home/apt,5250,1,0,5250.0
3774,SUPER BOWL Brooklyn Duplex Apt!!,Entire home/apt,6500,1,0,6500.0
3782,3 Bedroom Apartment,Entire home/apt,2750,1,0,2750.0
3785,Penthouse with Private Rooftop for Events/Shoots,Entire home/apt,2500,1,0,2500.0
3788,Prime NYC Location for Super Bowl,Entire home/apt,3750,1,0,3750.0
4376,Photography Location,Entire home/apt,4500,1,365,4500.0
4377,Film Location,Entire home/apt,8000,1,365,8000.0
5839,Columbus Circle and Park Views,Entire home/apt,2695,1,0,2695.0
6620,SOHO GALLERY,Entire home/apt,2400,1,365,2400.0
15560,Luxury townhouse Greenwich Village,Entire home/apt,6000,1,0,6000.0
20551,Spectacular Townhouse 4Floor 5BD West Village NYC,Entire home/apt,2590,1,361,2590.0
21821,The Otheroom Bar/Event/Filming Space -read det...,Entire home/apt,4000,1,173,4000.0
22353,Victorian Film location,Entire home/apt,5000,1,344,5000.0
22373,West Chelsea Studios - Penthouse 12,Private room,2800,1,89,2800.0
22992,"Modern Townhouse for Photo, Film & Daytime Ev...",Entire home/apt,2900,1,180,2900.0
25825,Fulton 2,Entire home/apt,5000,2,0,2500.0
26739,Broadway 1,Entire home/apt,5000,2,0,2500.0
28727,The room boom,Private room,3000,1,90,3000.0
28945,Chelsea Gallery Space for events and exhibitions,Private room,2010,1,364,2010.0
28946,Chelsea Gallery Space for events and exhibitions,Private room,3210,1,364,3210.0
28947,"Chelsea Gallery for events, exhibitions, fashion",Entire home/apt,4160,1,364,4160.0
29662,East 72nd Townhouse by (Hidden by Airbnb),Entire home/apt,7703,1,146,7703.0
29663,East 7th Street III by (Hidden by Airbnb),Entire home/apt,3518,1,215,3518.0
29664,Park Avenue Mansion by (Hidden by Airbnb),Entire home/apt,6419,1,45,6419.0
29665,Park Place Townhouse by (Hidden by Airbnb),Entire home/apt,2626,1,31,2626.0
29666,Prospect Place by (Hidden by Airbnb),Entire home/apt,2103,1,20,2103.0
30260,SHOOTS ONLY - Huge Artist loft in Williamsburg,Entire home/apt,2500,1,140,2500.0
34851,A Night at Anchor Aboard Yacht Ventura,Entire home/apt,3750,1,365,3750.0
38000,4-Floor Unique Event Space 50P Cap. - #10299B,Entire home/apt,5000,1,150,5000.0
38223,Luxury West Village private Townhouse 5B Garden,Entire home/apt,3000,1,365,3000.0
38498,"LUXURIOUS 5 bedroom, 4.5 bath home",Entire home/apt,2999,1,0,2999.0
38947,Times Square Palace,Entire home/apt,3000,1,311,3000.0
41216,West 88th Street by (Hidden by Airbnb),Entire home/apt,3512,1,124,3512.0
42523,70' Luxury MotorYacht on the Hudson,Entire home/apt,7500,1,364,7500.0
42542,West 84th Street by (Hidden by Airbnb),Entire home/apt,3613,1,158,3613.0
44034,3000 sq ft daylight photo studio,Entire home/apt,6800,1,364,6800.0
45185,Beautiful Brooklyn Brownstone Production Space,Entire home/apt,2500,1,168,2500.0
45666,Gem of east Flatbush,Private room,7500,1,179,7500.0

In [87]:
df3 = df2.copy()
df3 = df2[(df2['price_per_night']>min_throught) & (df2['price_per_night']<max_throught)]
df3

,name,room_type,price,minimum_nights,availability_365,price_per_night
0,Clean & quiet apt home by the park,Private room,149,1,365,149.0
1,Skylit Midtown Castle,Entire home/apt,225,1,355,225.0
9,Cute & Cozy Lower East Side 1 bdrm,Entire home/apt,150,1,188,150.0
16,Perfect for Your Parents + Garden,Entire home/apt,215,2,321,107.5
17,Chelsea Perfect,Private room,140,1,12,140.0
...,...,...,...,...,...,...
48862,Private room in a nice Brooklyn apartment,Private room,130,1,83,130.0
48873,Brooklyn paradise,Entire home/apt,170,1,363,170.0
48875,Welcome all as family,Private room,140,1,180,140.0
48880,The Raccoon Artist Studio in Williamsburg New ...,Entire home/apt,120,1,365,120.0
48887,Garden Jewel Apartment in Williamsburg New York,Entire home/apt,170,1,365,170.0

In [88]:
df3.describe()

              price  minimum_nights  availability_365  price_per_night
count   9721.000000     9721.000000       9721.000000      9721.000000
mean     283.216542        1.627405        125.774303       185.130879
std      361.590151        1.972299        135.893727       152.730643
min       97.000000        1.000000          0.000000        97.000000
25%      139.000000        1.000000          0.000000       110.500000
50%      200.000000        1.000000         72.000000       140.000000
75%      300.000000        2.000000        258.000000       200.000000
max    10000.000000      100.000000        365.000000      1999.800000

In [89]:
upper = df3.price_per_night.mean() + 4* df3.price_per_night.std()
lower = max(0,df3.price_per_night.mean() - 4* df3.price_per_night.std())
upper,lower

(np.float64(796.0534515185086), 0)

In [90]:
df3[(df3.price_per_night>upper) | (df3.price_per_night<lower) ]

,name,room_type,price,minimum_nights,availability_365,price_per_night
85,perfect for a family or small group,Entire home/apt,800,1,7,800.0
1105,$ (Phone number hidden by Airbnb) weeks - room f,Private room,1300,1,0,1300.0
1553,UWS renovated 2bedroom 2bath near everything.,Entire home/apt,900,1,365,900.0
1862,"Sunny, Family-Friendly 2 Bedroom",Entire home/apt,4000,4,83,1000.0
1910,A Little Palace in Brooklyn for Shoots and Events,Entire home/apt,800,1,365,800.0
...,...,...,...,...,...,...
47063,JAVITS Beautiful Stay for your NYC Vacation *****,Entire home/apt,843,1,358,843.0
48282,VJ'S 5 HOUR YACHT TOUR,Entire home/apt,1000,1,90,1000.0
48523,"Tasteful & Trendy Brooklyn Brownstone, near Train",Entire home/apt,1369,1,349,1369.0
48535,"Stunning & Stylish Brooklyn Luxury, near Train",Entire home/apt,1749,1,303,1749.0
48839,Massage Spa. Stay overnight. Authors Artist dr...,Private room,800,1,23,800.0

In [91]:
df3  = df3[(df3.price_per_night<upper) & (df3.price_per_night>lower)]
df3

,name,room_type,price,minimum_nights,availability_365,price_per_night
0,Clean & quiet apt home by the park,Private room,149,1,365,149.0
1,Skylit Midtown Castle,Entire home/apt,225,1,355,225.0
9,Cute & Cozy Lower East Side 1 bdrm,Entire home/apt,150,1,188,150.0
16,Perfect for Your Parents + Garden,Entire home/apt,215,2,321,107.5
17,Chelsea Perfect,Private room,140,1,12,140.0
...,...,...,...,...,...,...
48862,Private room in a nice Brooklyn apartment,Private room,130,1,83,130.0
48873,Brooklyn paradise,Entire home/apt,170,1,363,170.0
48875,Welcome all as family,Private room,140,1,180,140.0
48880,The Raccoon Artist Studio in Williamsburg New ...,Entire home/apt,120,1,365,120.0
48887,Garden Jewel Apartment in Williamsburg New York,Entire home/apt,170,1,365,170.0

In [92]:
df3.describe()

              price  minimum_nights  availability_365  price_per_night
count   9575.000000     9575.000000       9575.000000      9575.000000
mean     267.425483        1.634256        125.117702       170.998466
std      320.527490        1.984828        135.327313        95.129835
min       97.000000        1.000000          0.000000        97.000000
25%      138.500000        1.000000          0.000000       110.000000
50%      200.000000        1.000000         71.000000       139.000000
75%      300.000000        2.000000        256.000000       199.000000
max    10000.000000      100.000000        365.000000       794.000000